### ISSUE TITLE
IIIF

### ISSUE THREAD

**Issue by ewg118** [metmuseum/openaccess#14]
The source for the page https://www.metmuseum.org/art/collection/search/246870 would seem to indicate a IIIF resource for an image (https://collectionapi.metmuseum.org/api/collection/v1/iiif/246870/1391928/main-image), but I am unable to ascertain the info.json path. If you are indeed serving IIIF resources, do you plan to make manifests available?

**Comment by andrewallred** [comment]
@ewg118 We are not currently serving IIIF resources. We'll let you know if that changes.
