### ISSUE TITLE
MetObjects.csv not accessible

### ISSUE THREAD

**Issue by antonycourtney** [metmuseum/openaccess#15]
This is probably a github LFS issue, but the MetObjects.csv file is not currently accessible via the download button, "View Raw" or via wget.

Using the Download button I get:

![image](https://user-images.githubusercontent.com/4683413/49710884-16064580-fbf1-11e8-91cb-3f2f077a5ecb.png)

Trying wget I get the following:
```sh
$ wget https://media.githubusercontent.com/media/metmuseum/openaccess/master/MetObjects.csv
--2018-12-09 20:27:01--  https://media.githubusercontent.com/media/metmuseum/openaccess/master/MetObjects.csv
Resolving media.githubusercontent.com (media.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to media.githubusercontent.com (media.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-12-09 20:27:01 ERROR 404: Not Found.
```

**Comment by andrewallred** [comment]
@antonycourtney As you suspected this appears to have been an issue with github. Thanks for letting us know however.
