### ISSUE TITLE
Request: query set of objects

### ISSUE THREAD

**Issue by erf** [metmuseum/openaccess#17]
I would like to request an API option for retreiving a list of objects, given a list of object ID's. 

Something like:
```
https://collectionapi.metmuseum.org/public/collection/v1/objects/1,4,6,23,67,323
```

Now if i want to retreive more than one object, i have to do multiple requests, which is slow.

Thank you!

**Comment by erf** [comment]
I would also like to request the total number of objects, without downloading all objects.

**Comment by erf** [comment]
I would also like to filter on just the objects that have images.

**Comment by jedahan** [comment]
They all seem like great ideas, but I think it would be easier to track these feature requests if you made them separate github issues.

**Comment by erf** [comment]
@jdiedrick last someone in charge here replied was 1.dec 2017, so i don't really have much hope for any of these changes. If the owner replies, i will make separate issues.

**Comment by spencerk** [comment]
Hi @erf 
I've split your requests in to separate tickets.  We are evaluating new features for the API, and will take your suggestions in to consideration.

Thanks for your interest!

**Comment by erf** [comment]
@spencerk any news on any new features for the API or a potential release date?

**Comment by erf** [comment]
Any news on this @spencerk ?
