### ISSUE TITLE
API is blocked

### ISSUE THREAD

**Issue by jcoyne** [metmuseum/openaccess#18]
When I write a python script (using `requests` library) to retrieve a url like: 

https://collectionapi.metmuseum.org/public/collection/v1/objects/324946

the response is:

```html
<html style="height:100%"><head><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no">
<meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"></head>
<body style="margin:0px;height:100%">
<iframe src="/_Incapsula_Resource?CWUDNSAI=20&xinfo=5-67367335-0%200NNN%20RT%281551818010502%2036%29%20q%280%20-1%20-1%200%29%20r%280%20-1%29%20B15%283%2c901868%2c0%29%20U18&incident_id=116030910212059510-389373089293844789&edet=15&cinfo=03000000" frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">
Request unsuccessful. Incapsula incident ID: 116030910212059510-389373089293844789</iframe>
</body></html>
```

**Comment by jcoyne** [comment]
My fault here.

**Comment by dyanakiev** [comment]
Hi, where you able to solve the issue?

**Comment by jcoyne** [comment]
I believe I hacked my way around this by visiting the site in a web browser, then copying the cookies I get into my harvester script:
https://github.com/sul-dlss/dlme-harvest/blob/master/met/ancient-near-east-art/harvest_identifiers.py#L11

Not really an ideal solution for an API, but I guess it worked.
