### ISSUE TITLE
Can't download images because of Incapsula CDN

### ISSUE THREAD

**Issue by yingchensbn** [metmuseum/openaccess#20]
Hi,
I'd like to download the images in an object, but because these images are on Incapsula CDN and it has a feature of identifying scrapers, I can't download the images using a script.
I'm getting this error:
```
<html>
    <head>
        <META NAME="robots" CONTENT="noindex,nofollow">
        <script src="/_Incapsula_Resource?SWJIYLWA=5074a744e2e3d891814e9a2dace20bd4,719d34d31c8e3a6e6fffd425f7e032f3">
</script>
        <body>
</body>
    </html>
```

**Comment by dyanakiev** [comment]
Hello, i just got the same issue, when trying to search or get an object. Hm any ideas?

**Comment by andrewallred** [comment]
@yingchensbn @dyanakiev We've adjusted some settings on our side and in theory you should no longer be encountering this issue. Could you try again and let us know? Thanks!

**Comment by dilpreetsingh** [comment]
@andrewallred I was having the same issue, and it seems resolved now! Thank you!
