### ISSUE TITLE
What are the search URLs in the .csv for? All seem to go to 404.

### ISSUE THREAD

**Issue by phobrain** [metmuseum/openaccess#28]
Title says it all. The csv was recently updated, so odd that dead links are a big part of it. E.g.

    http://www.metmuseum.org/art/collection/search/48,8/12/2019

I wonder why isn't there an obvious way to get the images.

**Comment by spencerk** [comment]
Looks like a parsing issue.  The metadatadate field is getting concatentated with the URL.  

Here's how it should look:
![Github-URL](https://user-images.githubusercontent.com/1399507/62898666-090f9800-bd24-11e9-9be6-37069b54c807.PNG)

**Comment by spencerk** [comment]
Currently, our images are only available via our API:
https://metmuseum.github.io/
