### ISSUE TITLE
Documentation: object begin/end dates are not strings

### ISSUE THREAD

**Issue by lukasschwab** [metmuseum/openaccess#30]
Hello! Looks like the [documentation page](https://metmuseum.github.io/#object) isn't open-source, so I can't open a PR to this effect. A couple of fields on the `Object` response have their types reported incorrectly:

| Field             	| Documented type 	| Correct type 	|
|-------------------	|-----------------	|--------------	|
| `objectBeginDate` 	| string          	| int          	|
| `objectEndDate`   	| string          	| int          	|

For instance, on https://collectionapi.metmuseum.org/public/collection/v1/objects/436535:

```json
{
  ....
  "objectBeginDate":1889,
  "objectEndDate":1889,
  ....
}
```

Proposed fix: updating the documented types.

**Comment by spencerk** [comment]
Resolved  02/27/20
