### ISSUE TITLE
Is it alright to hotlink images?

### ISSUE THREAD

**Issue by ognjenio** [metmuseum/openaccess#37]
Or must I copy them?

**Comment by spencerk** [comment]
Hi

Sorry for the delay.

Hotlinking is preferable to scraping, but we do have a rate limit on requests (80/second).

Feel free to get in touch if you run in to issues.  Would also love to hear how you are using the API.  

Best,

Spencer

**Comment by spencerk** [comment]
Also be aware that image links could become unavailable or change for various reasons.  That said, the API has the most recent data, so you should be good if you use that.

**Comment by ognjenio** [comment]
Understood, thanks for the reply.

Will let you know once I've got something to show.
