### ISSUE TITLE
Security Certificate Expired for collectionapi.metmuseum.org

### ISSUE THREAD

**Issue by gskinner** [metmuseum/openaccess#41]
The API is currently inaccessible via secure connections because the security certificate expired today at 5 pm Eastern.

<img width="697" alt="image" src="https://user-images.githubusercontent.com/157128/186784556-21c75c63-a8aa-4e10-afd2-514073a9d52f.png">

**Comment by gskinner** [comment]
As an additional note, the certificate for the image server expires in a couple of months also (Oct 22).
<img width="602" alt="image" src="https://user-images.githubusercontent.com/157128/186786855-b71fc2e6-738f-4088-8688-917594eb70e6.png">

**Comment by gskinner** [comment]
Last note, this is also causing issues on the main site:
https://www.metmuseum.org/exhibitions/listings/2021/afrofuturist-period-room/exhibition-objects
<img width="646" alt="image" src="https://user-images.githubusercontent.com/157128/186789586-cde2ce87-2750-49f8-af42-b0e255760594.png">

While I'm here: Thanks for the amazing API!

**Comment by stephenhmarsh** [comment]
Thanks for reporting @gskinner. Not sure how this happened but I've forwarded this to our IT team.

**Comment by stephenhmarsh** [comment]
They fixed it thanks to your report.  Much appreciated.

**Comment by gskinner** [comment]
Amazing. Thanks again!
