### ISSUE TITLE
I want to ask the meaning of “This work” in third paragraph in README.md

### ISSUE THREAD

**Issue by xinyu3ru** [metmuseum/openaccess#9]
I‘m translating the README.md file into Chinese，I'm puzzled by 
`To the extent possible under law, The Metropolitan Museum of Art has waived all copyright and related or neighboring rights to this dataset using Creative Commons Zero. This work is published from: The United States Of America. You can also find the text of the CC Zero deed in the file LICENSE in this repository. `
"This work" means the dataset work or the CCZero document?

In front of the sentence, it's a dot . In Chinese case , it means CCZero document, otherwise it should be a momma.

**Comment by tswast** [comment]
My interpretation is that it refers to the dataset (e.g. the CSV file in this repository).

The Creative Commons may have a Chinese translation off the CC Zero license that you can use as a reference. https://creativecommons.org/publicdomain/zero/1.0/

**Comment by xinyu3ru** [comment]
Thank you for your reply.
They have translate plan also want a meeting in 2015，but they still not finish that translate yet.
I will start that work when I finish this translation.

**Comment by xinyu3ru** [comment]
Translation finished. I did not pull back.
I put in my branch [The Met openaccess](https://github.com/xinyu3ru/openaccess)
[Translation File](https://github.com/xinyu3ru/openaccess/blob/master/locale/README_Zh-CN.md)
